title: Epicycle.Math (.NET)
url: https://github.com/open-epicycle/Epicycle.Math-cs
summary: "Epicycle .NET math library. Includes: 2D/3D geometry, polygons, linear algebra, differential geometry, stochastic processes, Kalman filter."

organization: Epicycle
tags: epicycle math vectors matrices geometry 2D 3D polygons multiploygons linear algebra differential geometry stochastic process kalman filter lib library util utilities c#
copyright: Copyright 2015 Epicycle
license_url: http://www.apache.org/licenses/LICENSE-2.0

release_notes: https://github.com/open-epicycle/Epicycle.Math-cs/blob/ver-$version$/README.md

dotnet_frameworks:
 - net45

nuget_dependencies:
 - Epicycle.Commons-cs.0.1.4.0
 - MathNet.Numerics.3.4.0

description: |
   Epicycle .NET math library. Includes: 2D/3D geometry, polygons, linear algebra, differential geometry, stochastic processes, Kalman filter.
   
   * Details & release notes: https://github.com/open-epicycle/Epicycle.Math-cs/blob/ver-$version$/README.md
   * Sources: https://github.com/open-epicycle/Epicycle.Math-cs/tree/ver-$version$
   * Git repository: https://github.com/open-epicycle/Epicycle.Math-cs