title: Epicycle.Math (.NET)
url: https://github.com/open-epicycle/Epicycle.Math-cs
summary: TODO

organization: Epicycle
tags: TODO
copyright: Copyright 2015 Epicycle
license_url: http://www.apache.org/licenses/LICENSE-2.0

release_notes: https://github.com/open-epicycle/Epicycle.Math-cs/blob/ver-$version$/README.md

dotnet_frameworks:
 - net45

nuget_dependencies:
 - Epicycle.Commons-cs.0.1.3.0
 - MathNet.Numerics.3.4.0

description: |
   TODO